### ISSUE TITLE
ERR re-enqueueing failed block err="failed to get block results from node"

### ISSUE THREAD

**Issue by npow** [forbole/juno#39]
Hi, I tried running juno (branch `v2/cosmos-stargate`) against a localnet using [`cosmos-sdk/mainline`](https://github.com/cosmos/cosmos-sdk/commit/7e3c6ae759b95eb83e81095e8664ed5f457df585) and am getting the following error. 

```
ERR re-enqueueing failed block err="failed to get block results from node: error unmarshalling result: illegal base64 data at input byte 44" height=2
```

* go version: go version go1.17.1 darwin/amd64
* OS: macOS 10.15.7

**Q**: Am I doing something wrong? I'm not entirely sure about the juno branch, but I also tried running against v0.40.0 of cosmos-sdk and got the same error. If you could provide instructions on how to run juno against a localnet that would be great (or alternatively, a public remote RPC endpoint I could use instead).

Steps taken:
1. start local testnet using `build/simd testnet start`
2. followed juno setup instructions [here](https://github.com/forbole/juno/blob/v2/cosmos-stargate/.docs/setup.md)
3. run `juno parse` 

Full error:
```
➜  juno  juno parse                                                                                                                                                                              [7:41:50]
7:41AM DBG starting worker... number=1
7:41AM INF listening for new block events...
7:41AM INF syncing missing blocks... latest_block_height=128
7:41AM DBG enqueueing missing block height=1
7:41AM DBG enqueueing missing block height=2
7:41AM DBG enqueueing missing block height=3
7:41AM DBG enqueueing missing block height=4
7:41AM DBG enqueueing missing block height=5
7:41AM DBG enqueueing missing block height=6
7:41AM DBG enqueueing missing block height=7
7:41AM DBG enqueueing missing block height=8
7:41AM DBG enqueueing missing block height=9
7:41AM DBG enqueueing missing block height=10
7:41AM DBG enqueueing missing block height=11
7:41AM DBG enqueueing missing block height=12
7:41AM DBG enqueueing missing block height=13
7:41AM DBG enqueueing missing block height=14
7:41AM DBG enqueueing missing block height=15
7:41AM DBG enqueueing missing block height=16
7:41AM DBG enqueueing missing block height=17
7:41AM DBG enqueueing missing block height=18
7:41AM DBG enqueueing missing block height=19
7:41AM DBG enqueueing missing block height=20
7:41AM DBG enqueueing missing block height=21
7:41AM DBG enqueueing missing block height=22
7:41AM DBG enqueueing missing block height=23
7:41AM DBG enqueueing missing block height=24
7:41AM DBG enqueueing missing block height=25
7:41AM DBG enqueueing missing block height=26
7:41AM DBG enqueueing missing block height=27
7:41AM DBG processing block height=1
7:41AM DBG enqueueing missing block height=28
7:41AM ERR re-enqueueing failed block err="failed to get block results from node: error unmarshalling result: illegal base64 data at input byte 44" height=2
<SNIPPED>
```

config.yaml:
```
chain:
    bech32_prefix: cosmos
    modules: []
node: 
  type: remote
  config: 
    rpc:
      client_name: juno
      address: tcp://localhost:26657
      max_connections: 20
    grpc:
      insecure: true
      address: localhost:9090
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
database:
    name: juno_cosmos
    host: localhost
    port: 5432
    user: <REDACTED>
    password: <REDACTED>
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
logging:
    level: debug
    format: text
```

simd status:
```
➜  cosmos-sdk  ./build/simd status | jq                                                                                                                                                          [7:39:45]
{
  "NodeInfo": {
    "protocol_version": {
      "p2p": "8",
      "block": "11",
      "app": "0"
    },
    "id": "014087327cd3d8c910e5aeac24c0c737b14a1daf",
    "listen_addr": "tcp://0.0.0.0:60886",
    "network": "chain-QiaZfv",
    "version": "0.35.0-unreleased",
    "channels": "402021222330386061626300",
    "moniker": "node0",
    "other": {
      "tx_index": "on",
      "rpc_address": "tcp://0.0.0.0:26657"
    }
  },
  "SyncInfo": {
    "latest_block_hash": "515B749AE841F2ED8FD02595440D2D293716DD29B088723289F4321F713DE046",
    "latest_app_hash": "AFC907CC6D21A0E7E6446D7F5C40A95797045B09A8A817604C8CF97BDCB0A85A",
    "latest_block_height": "271",
    "latest_block_time": "2022-01-02T07:47:42.914668Z",
    "earliest_block_hash": "1DBC94BC887584899097C1079D121B2ABF9516C18B7B744A36C57756150BD91F",
    "earliest_app_hash": "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855",
    "earliest_block_height": "1",
    "earliest_block_time": "2022-01-02T07:36:17.395216Z",
    "max_peer_block_height": "0",
    "catching_up": false,
    "total_synced_time": "0",
    "remaining_time": "0",
    "total_snapshots": "0",
    "chunk_process_avg_time": "0",
    "snapshot_height": "0",
    "snapshot_chunks_count": "0",
    "snapshot_chunks_total": "0",
    "backfilled_blocks": "0",
    "backfill_blocks_total": "0"
  },
  "ValidatorInfo": {
    "Address": "E420BD19C497E72AEB573F3455E62E6EFDDF2103",
    "PubKey": {
      "type": "tendermint/PubKeyEd25519",
      "value": "rWIMw4FacZKmej+hs+xz5MfcDeLdFvIOPZ2s20lc2UI="
    },
    "VotingPower": "100"
  }
}
```
