### ISSUE TITLE
Bad handshake with Stargate

### ISSUE THREAD

**Issue by rmontagnin** [forbole/juno#6]
## Description
As reported inside forbole/bdjuno#55, Juno seems to not work when trying to connect to Stargate. 

## Branch
```
cosmos-v0.39.x
```

## Configuration
```toml
rpc_node = "http://rpc.stargate.bigdipper.live:80"
client_node = "http://api.stargate.bigdipper.live:443"
```

## Log
```
{"level":"debug","time":"2020-10-08T09:28:50+02:00","message":"Reading config file"}
ERROR: websocket: bad handshake: failed to start RPC client
```
